name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
            -   name: Setup Jfrog CLI 
                uses: jfrog/setup-jfrog-cli@v4
                with:
                    version: latest
                env:
                        # JFrog platform url (for example: https://acme.jfrog.io)
                        JF_URL: ${{ secrets.JF_URL }}
                        # JFrog platform access token (if JF_USER and JF_PASSWORD are not provided)
                        # JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
                  
                    
            -   name: Artifactory check connection
                run: jf rt ping 